name: Deploy to Local Linux

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: [self-hosted, Linux, X64, nikhil-Predator-PH315-51]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Ensure deployment directory exists
        run: mkdir -p ~/drone-deployment

      - name: Copy project to deployment directory
        run: |
          rsync -av --delete $GITHUB_WORKSPACE/ ~/drone-deployment/

      - name: Pull latest Docker image
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/drone-server:latest

      - name: Deploy stack using docker-compose
        run: |
          cd ~/drone-deployment
          docker compose down
          docker compose up -d

